---
title: "Syllabus for Probability and Statistics"
author: "Matt Rissler, PhD"
date: "August 29, 2017"
output: ioslides_presentation
---

##Course Information

|Type        | Information|
|-----------:|:---------------------------|
|Course Title| Probability and Statistics|
|Course Number| MAT 220|
|Credit Hours | 3|
|Meeting Time | MWF 10:00-10:50|
|Meeting Location | HENN 270 |
|Instructor | Matt Rissler, PhD|
|Prerequisites | MAT 150 and (MAT 160 or CIT 115)|

##Instructor Information

|Type        | Information|
|-----------:|:---------------------------|
|Email| matthew.rissler@loras.edu|
|Office Phone | 563.588.7792 |
|Office | HENN 209 |
|twitter  | [\@discnerd](https://twitter.com/discnerd) |

##Office Hours

|Day     |Time   |Location|
|--------:|:------|:---------|
|Monday | 11:00am-12:00pm | HENN 209|
|Tuesday, Thursday | 9am-12pm | HENN 209|
|Tuesday | 6:30-7:30pm | HENN 250 (Tasty Tuesdays) |
| Friday| 11:00am-1:00pm | Math Lab (Headwaters)|

## Other Help

 * [Math Lab](https://docs.google.com/spreadsheets/d/1rA5WV6vNb95eiwjJVkEpyUtkbCREWeLSZYJALpo4Ivc/edit?usp=sharing) (Click for schedule.)

 * Thursday Nights at the Heidenreich's



# Resources

## Textbooks

* OpenIntro Statistics, 3rd Ed. Diez, Barr and Cetinkaya-Rundel, ISBN 978-1943450053, 2015. Available at <https://www.openintro.org/stat/textbook.php?stat_book=os>.

* Introduction to Probability, 2nd Ed. Grinstead and Snell. AMS ISBN 0-8218-0749-8, 1997. Also available as a pdf at <http://goo.gl/XWSro>.



##Software

* R   <https://cran.r-project.org/bin/windows/base/>
* RStudio  <https://www.rstudio.com/products/rstudio/download2/>
* various packages in R
          

##Course Description
Data science is the process of collecting, cleaning, analyzing, summarizing and presenting data in a scalable and generalizable manner. In this course, students will learn each of these steps using appropriate software and techniques culminating in a project.

##Course Objectives

Students should:

1.	gain factual knowledge (terminology, classification, methods, etc.) in probability and statistics

2.	learn fundamental principles, generalizations, and theories in probability statistics

3.	learn to apply course material (to improve thinking, problem solving, and decision making)

4.	develop specific skills, competencies, and points of view needed by professionals in fields closely related to this course


##Learning Outcomes

1.  You will learn multiple probability distributions, both discrete and continuous, and learn to use them in appropriate manners.

2.	You will learn to calculate various statistics from a data set and what probability distributions they are related to.

3.	You will learn to draw conclusions about a data sets statistic based on the related probability distribution. (Hypothesis Testing)

4.	You will learn different sampling and experimental methods.

5.	You will learn to use the statistical software R.


#Assessment and Grading

##Homework
15% of the final grade - You are expected to complete homework by the time it is due.  Some homework will be assigned on WeBWorK and some on eLearn and is to be turned in to me, or my office by the time it is due.  This will usually be 7:30pm on Tuesday.

##Quizzes
10% of the final grade - There will be a quiz on a weekly basis on the topics from the last homework assignment.

##Project
20% of the final grade - You will work in groups of 3ish people to analyze data of your selection.  You will be required to create a report and make a presentation.

## Exams
25% of the final grade each - We will have two exams in this course. Each will include an in-class portion and a take-home portion. The take-home portion will be due on eLearn.   Failure to attend an exam will result in a zero on the in-class portion.

## Math Culture
5% if the final grade - You are required to accrue at least 20 Math Culture points over the space of the semester.  More information about culture points can be found on eLearn. Culture points are intended to expose you to a broader and deeper scope of mathematics than is available in the courses offered at Loras.

#Policies

##Academic Dishonesty 

Please refer to the Loras College Academic Honesty Policy.  It can be found at <http://lorasedu.sharepoint.com/Academics/IQ/Documents/Academic%20Honesty%20Policy.doc>

##Learning Disabilities

In accordance with federal law, if you have a diagnosed disability or believe that you have a disability that might require reasonable accommodations, please feel free to discuss your needs with me at your earliest convenience.  Documentation of your disability must be on file with the Office of Disability Services (ODS), 120 Academic Resource Center, (563-588-7134) for you to receive accommodations. 

##Expectation for Class Attendance

You are expected to attend every class.  If you are going to miss class, email me beforehand.  Assignments will be given in class randomly.  Attendance will not be taken, but it will be obvious if you are not there. Note the policy for missed activities and exams.

##Withdrawal Date

 - The last day to add a semester-long course is Friday, September 1.
 - The last day to withdraw from this class without a ‘W’ is Friday, September 15. 
 - The last day to withdraw with a grade of ‘W’ is Friday, October 27.


##Tentative Schedule


|Week| Topic(s)|
|----|---------|
| 1  | Intro to Class/R/RMarkdown|
| 2  | Vizualizing Data/Where Data Comes From |
| 3  | Discrete Probability |
| 4  | Continuous Probability |
| 5  | Combinatorics |
| 6  | Conditional Probability |
| 7  | Distributions |

## Tentative Schedule continued

|Week| Topic(s)|
|----|---------|
| 8  | Expected Value and Variance |
| 9  | Sum of Variables |
| 10 | Confidence Intervals |
| 11 | Hypothesis Tests |
| 12-16 | More Tests and Projects | 




